# dim-ls completions for fish shell

complete -c dim-ls -s a -l all -d "do not ignore entries starting with ."
complete -c dim-ls -s A -l almost-all -d "do not list implied . and .."
complete -c dim-ls -s B -l ignore-backups -d "do not list implied entries ending with ~"
complete -c dim-ls -s c -d "with -lt: sort by, show ctime; with -l: show ctime; else: sort by ctime"
complete -c dim-ls -s C -d "list entries by columns"
complete -c dim-ls -l color -r -d "colorize output" -xa "always auto never"
complete -c dim-ls -s d -l directory -d "list directory entries instead of contents"
complete -c dim-ls -s D -l dired -d "generate output designed for Emacs' dired mode"
complete -c dim-ls -s e -l tree -d "list directories in a tree-like format"
complete -c dim-ls -s F -l classify -d "append indicator (*/=>@|) to entries"
complete -c dim-ls -l file-type -d "append indicator except *"
complete -c dim-ls -l git -d "show git status for each file"
complete -c dim-ls -s G -l no-group -d "in long listing, don't print group names"
complete -c dim-ls -l group-directories-first -d "group directories before files"
complete -c dim-ls -s h -l human-readable -d "print sizes in human readable format"
complete -c dim-ls -s H -l dereference-command-line -d "follow symlinks listed on command line"
complete -c dim-ls -s i -l inode -d "print index number of each file"
complete -c dim-ls -s l -d "use a long listing format"
complete -c dim-ls -s L -l dereference -d "follow symbolic links"
complete -c dim-ls -s m -d "fill width with comma separated list"
complete -c dim-ls -s n -l numeric-uid-gid -d "list numeric user and group IDs"
complete -c dim-ls -s N -l literal -d "print raw entry names"
complete -c dim-ls -s o -d "like -l, but do not list group information"
complete -c dim-ls -s p -l indicator-style -r -d "append / to directories" -xa "slash"
complete -c dim-ls -s q -l hide-control-chars -d "print ? instead of non graphic characters"
complete -c dim-ls -s Q -l quote-name -d "enclose entry names in double quotes"
complete -c dim-ls -s r -l reverse -d "reverse order while sorting"
complete -c dim-ls -s R -l recursive -d "list subdirectories recursively"
complete -c dim-ls -s s -l size -d "print allocated size in blocks"
complete -c dim-ls -s S -d "sort by file size"
complete -c dim-ls -l sort -r -d "sort by WORD" -xa "none extension size time version"
complete -c dim-ls -s t -d "sort by modification time"
complete -c dim-ls -s T -l tabsize -r -d "assume tab stops at each COLS"
complete -c dim-ls -l time -r -d "show time as WORD" -xa "atime access use ctime status"
complete -c dim-ls -s u -d "sort by, show access time"
complete -c dim-ls -s U -d "do not sort; list in directory order"
complete -c dim-ls -s v -l version -d "output version information and exit"
complete -c dim-ls -s w -l width -r -d "assume screen width"
complete -c dim-ls -s x -d "list entries by lines instead of columns"
complete -c dim-ls -s X -d "sort alphabetically by extension"
complete -c dim-ls -s Z -l octal-permissions -d "show file permissions in octal format"
complete -c dim-ls -s 1 -d "list one file per line"
complete -c dim-ls -l help -d "display this help and exit"
