# fish completion for dim-ls
function __fish_dim_ls_using_command
    set -l cmd (commandline -opc)
    if [ (count $cmd) -gt 1 ]
        return 0
    end
    return 1
end

complete -c dim-ls -s a -l all -d "do not ignore entries starting with ."
complete -c dim-ls -s A -l almost-all -d "do not list implied . and .."
complete -c dim-ls -s B -l ignore-backups -d "do not list implied entries ending with ~"
complete -c dim-ls -s c -d "with -lt: sort by, and show, ctime"
complete -c dim-ls -s C -d "list entries by columns"
complete -c dim-ls -l color -d "colorize the output" -xa "always auto never"
complete -c dim-ls -s d -l directory -d "list directory entries instead of contents"
complete -c dim-ls -s D -l dired -d "generate output designed for Emacs' dired mode"
complete -c dim-ls -s e -l tree -d "list directories in a tree-like format"
complete -c dim-ls -s F -l classify -d "append indicator (*/=@|) to entries"
complete -c dim-ls -l file-type -d "like --classify, except do not append *"
complete -c dim-ls -l git -d "show git status for each file"
complete -c dim-ls -s G -l no-group -d "in a long listing, don't print group names"
complete -c dim-ls -l group-directories-first -d "group directories before files"
complete -c dim-ls -s h -l human-readable -d "print sizes in human readable format"
complete -c dim-ls -s i -l inode -d "print the index number of each file"
complete -c dim-ls -s l -d "use a long listing format"
complete -c dim-ls -s L -l dereference -d "follow symbolic links"
complete -c dim-ls -s m -d "fill width with a comma separated list of entries"
complete -c dim-ls -s n -l numeric-uid-gid -d "list numeric user and group IDs"
complete -c dim-ls -s N -l literal -d "print raw entry names"
complete -c dim-ls -s o -d "like -l, but do not list group information"
complete -c dim-ls -s p -l indicator-style -d "append / indicator to directories" -xa "slash"
complete -c dim-ls -s q -l hide-control-chars -d "print ? instead of non graphic characters"
complete -c dim-ls -s Q -l quote-name -d "enclose entry names in double quotes"
complete -c dim-ls -s r -l reverse -d "reverse order while sorting"
complete -c dim-ls -s R -l recursive -d "list subdirectories recursively"
complete -c dim-ls -s s -l size -d "print the allocated size of each file in blocks"
complete -c dim-ls -s S -d "sort by file size"
complete -c dim-ls -l sort -d "sort by WORD" -xa "none extension size time name"
complete -c dim-ls -l time -d "show time as WORD" -xa "atime access use ctime status"
complete -c dim-ls -s t -d "sort by modification time"
complete -c dim-ls -s T -l tabsize -d "assume tab stops at each COLS" -xa "2 4 8"
complete -c dim-ls -s u -d "sort by, and show, access time"
complete -c dim-ls -s U -d "do not sort; list entries in directory order"
complete -c dim-ls -s v -l version -d "output version information and exit"
complete -c dim-ls -s w -l width -d "assume screen width" -xa "80 120 160"
complete -c dim-ls -s x -d "list entries by lines instead of by columns"
complete -c dim-ls -s X -d "sort alphabetically by entry extension"
complete -c dim-ls -s Z -l octal-permissions -d "show file permissions in octal format"
complete -c dim-ls -s 1 -d "list one file per line"
complete -c dim-ls -l help -d "display this help and exit"
